# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: /
  #   weight: 1
  - name: Me
    url: about
    weight: 100

  - parent: Me
    name: my profile
    url: people
    weight: 210
  - parent: Me
    name: my information
    url: tour
    weight: 630

  - parent: Favorites
    name: 미피
    url: publication
    weight: 310

  # - name: Projects
  #   url: project
  #   weight: 400


  # - name: Coursework
  #   url: publication
  #   weight: 500

  - parent: More
    name: 추천
    url: post
    weight: 620
  - parent: 여러 가지
    name: 소식
    url: event
    weight: 630


  - name: Contact
    url: contact
    weight: 700