# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Y
    url: /#papers
    weight: 11
  - name: U
    url: /#talks
    weight: 12
  - name: B
    url: /#news
    weight: 13
  - name: I
    url: experience/
    weight: 20
  - name: N
    url: projects/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
