# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: /
  #   weight: 1
  - name: Me
    url: about
    weight: 100

  - name: Favorites
    url: people
    weight: 200
  - parent: Me
    name: my profile
    url: /author/이경수/
    weight: 210
  - parent: Me
    name: my friends
    url: people
    weight: 220

  - name: Travel
    url: publication
    weight: 300
  - parent: Research
    name: Recommend
    url: publication
    weight: 310
  - parent: Research
    name: Etc
    url: field
    weight: 320

  # - name: Projects
  #   url: project
  #   weight: 400


  # - name: Coursework
  #   url: publication
  #   weight: 500

  - name: 
    url: post
    weight: 600
  - parent: Inform
    name: Notifications
    url: notification
    weight: 610
  - parent: Inform
    name: News
    url: post
    weight: 620
  - parent: Inform
    name: Event
    url: event
    weight: 630


  - name: Contact
    url: contact
    weight: 700